name: CI
on:
   workflow_dispatch:
   push:
      branches:
         - "master"
   pull_request:
      types:
         - closed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm install
      - run: npm run ci

      - name: Create a PR for deployment
        uses: peter-evans/create-pull-request@v3
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         branch: aws-s3-deploy
         title: 'S3 AWS Bucket Deployment'
         body: 'Merge this branch to deploy to AWS S3 Bucket.'
         labels: 'enhancement'

  deploy_to_aws_s3:
   needs: build
   if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'aws-s3-deploy'
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: 16.x
         cache: 'npm'

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-west-1
         
     - name: Deploy to S3 bucket
       run: npm run deploy