name: CI
on:
   workflow_dispatch:
   push:
      branches:
         - "master"
      
jobs:
  build:
    if: github.event_name != 'pull_request' || (github.event.pull_request.base.ref != 'master' && github.event.pull_request.head.ref != 'aws-s3-deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm install
      - run: npm run ci

      - name: Create a PR for deployment
        uses: peter-evans/create-pull-request@v5
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         branch: deploy-to-aws-s3
         title: 'S3 AWS Bucket Deployment'
         body: 'Merge this branch to deploy to AWS S3 Bucket.'
         labels: 'enhancement'